# syntax=docker/dockerfile:1

FROM rust:1.94.0-slim-bookworm AS builder

WORKDIR /nomos-testing
COPY --from=nomos_testing . /nomos-testing

RUN apt-get update && apt-get install -yq \
    git gcc g++ clang libssl-dev pkg-config ca-certificates curl \
    && rm -rf /var/lib/apt/lists/*

RUN cargo build --locked --release \
    -p cfgsync-runtime \
    --bins

FROM debian:bookworm-slim AS base

RUN apt-get update && apt-get install -yq \
    libstdc++6 libssl3 ca-certificates curl \
    && rm -rf /var/lib/apt/lists/*

COPY --from=builder /nomos-testing/target/release/cfgsync-server /usr/bin/cfgsync-server
COPY --from=builder /nomos-testing/target/release/cfgsync-client /usr/bin/cfgsync-client

ENTRYPOINT ["/usr/bin/cfgsync-server"]
