use core::{
    num::{NonZeroU64, NonZeroU128},
    pin::Pin,
    task::{Context, Poll},
};

use futures::{Stream, StreamExt as _};
use tracing::trace;

use crate::message_scheduler::round_info::Round;

const LOG_TARGET: &str = "blend::scheduling::cover";

/// A scheduler for cover messages that can yield a new cover message when
/// polled, as per the specification.
pub struct SessionCoverTraffic<Rng, RoundClock> {
    /// The clock ticking at the beginning of each new round.
    round_clock: RoundClock,
    /// The number of cover messages still to be emitted.
    remaining_messages: u64,
    /// The number of rounds remaining in this session (including the current
    /// one).
    remaining_rounds: Round,
    /// The count of data messages generated by the node that have not yet been
    /// accounted for by the scheduler.
    ///
    /// This is decreased every time this scheduler should emit a new cover
    /// message, but does not.
    unprocessed_data_messages: usize,
    /// The RNG used to decide whether a round is a release round and whether
    /// a cover message should be released if there's unprocessed messages.
    rng: Rng,
}

impl<Rng, RoundClock> SessionCoverTraffic<Rng, RoundClock>
where
    Rng: rand::Rng,
{
    /// Initialize the scheduler with the required details.
    pub fn new(
        Settings {
            additional_safety_intervals,
            expected_intervals_per_session,
            rounds_per_interval,
            message_count,
        }: Settings,
        rng: Rng,
        round_clock: RoundClock,
    ) -> Self {
        let total_intervals = expected_intervals_per_session
            .get()
            .checked_add(additional_safety_intervals)
            .expect("Overflow when calculating total intervals per session.");
        let total_rounds = total_intervals
            .checked_mul(rounds_per_interval.get())
            .expect("Overflow when calculating total rounds per session.");
        trace!(target: LOG_TARGET, "Creating new cover message scheduler with {total_rounds} total rounds.");

        assert!(
            message_count <= total_rounds,
            "The number of messages to emit must be at most the total number of rounds."
        );

        Self {
            round_clock,
            remaining_messages: message_count,
            remaining_rounds: u128::from(total_rounds).into(),
            unprocessed_data_messages: 0,
            rng,
        }
    }

    /// Consider the current round a release round with probability
    /// `remaining_messages / remaining_rounds`. If it is a release round:
    /// * Emit a cover message if there are no unprocessed data messages, OR
    /// * Use a coin flip (weighted by unprocessed data messages / remaining
    ///   cover messages) to decide whether to skip the emission in favour of an
    ///   already-queued data message.
    fn consume_round(&mut self) -> bool {
        // We need to check this since we use it as a fraction denominator later on.
        let Ok(non_zero_unconsumed_remaining_rounds) =
            NonZeroU128::try_from(self.remaining_rounds.inner())
        else {
            assert!(
                self.remaining_messages == 0,
                "If there are no remaining rounds, there should be no remaining messages."
            );
            tracing::trace!(target: LOG_TARGET, "No remaining rounds.");
            return false;
        };
        // Update remaining rounds regardless of what we do next, since we are consuming
        // this round.
        self.remaining_rounds = (non_zero_unconsumed_remaining_rounds.get() - 1).into();

        // Decide whether this round is a release round based on the ratio of
        // messages still to emit over the rounds still available.
        let is_release_round = self.rng.gen_bool(
            self.remaining_messages as f64 / non_zero_unconsumed_remaining_rounds.get() as f64,
        );

        if !is_release_round {
            return false;
        }

        let non_zero_unconsumed_remaining_messages = NonZeroU64::try_from(self.remaining_messages)
            .expect("There should be at least one remaining message if this is a release round.");

        // This is a release round, so no matter if we end up releasing a new cover
        // message or not, we consume one quota.
        self.remaining_messages = non_zero_unconsumed_remaining_messages.get() - 1;

        if self.unprocessed_data_messages == 0 {
            return true;
        }

        // Coin flip to decide whether an unprocessed data message should
        // replace this cover message. The probability of skipping is
        // proportional to the number of unprocessed data messages relative to
        // the number of cover messages that were pending (before this one was
        // consumed).
        let should_skip = {
            let threshold = self.unprocessed_data_messages as f64
                / non_zero_unconsumed_remaining_messages.get() as f64;
            self.rng.gen_range(0f64..=1f64) <= threshold
        };
        if should_skip {
            self.unprocessed_data_messages = self.unprocessed_data_messages.saturating_sub(1);
            trace!(target: LOG_TARGET, "Release skipped because of data message.");
        }
        !should_skip
    }
}

impl<Rng, RoundClock> SessionCoverTraffic<Rng, RoundClock> {
    #[cfg(test)]
    pub const fn with_test_values(
        round_clock: RoundClock,
        remaining_messages: u64,
        remaining_rounds: Round,
        rng: Rng,
        unprocessed_data_messages: usize,
    ) -> Self {
        Self {
            round_clock,
            remaining_messages,
            remaining_rounds,
            unprocessed_data_messages,
            rng,
        }
    }

    #[cfg(test)]
    pub const fn unprocessed_data_messages(&self) -> usize {
        self.unprocessed_data_messages
    }

    /// Notify the scheduler that a new data message has been queued and will be
    /// released in the next round, which will result in one of the unscheduled
    /// cover messages from now to the end of the session to be randomly
    /// skipped.
    pub fn notify_new_data_message(&mut self) {
        self.unprocessed_data_messages = self
            .unprocessed_data_messages
            .checked_add(1)
            .expect("Overflow when incrementing unprocessed data messages.");
        trace!(target: LOG_TARGET, "New data message event registered. Unprocessed messages count: {}", self.unprocessed_data_messages);
    }
}

impl<Rng, RoundClock> Stream for SessionCoverTraffic<Rng, RoundClock>
where
    RoundClock: Stream<Item = Round> + Unpin,
    Rng: rand::Rng + Unpin,
{
    type Item = ();

    fn poll_next(mut self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Option<Self::Item>> {
        let new_round = match self.round_clock.poll_next_unpin(cx) {
            Poll::Ready(Some(new_round)) => new_round,
            Poll::Ready(None) => return Poll::Ready(None),
            Poll::Pending => return Poll::Pending,
        };

        // If a new cover message is scheduled...
        if self.consume_round() {
            trace!(target: LOG_TARGET, "Emitting new cover message for round {new_round}");
            return Poll::Ready(Some(()));
        }
        trace!(target: LOG_TARGET, "Not a pre-scheduled emission for round {new_round}.");
        // Awake to trigger a new round clock tick.
        cx.waker().wake_by_ref();
        Poll::Pending
    }
}

/// The settings to initialize the cover message scheduler.
#[derive(Debug, Clone, Copy)]
pub struct Settings {
    /// The number of intervals to use as the safety buffer in case of longer
    /// sessions, as per the spec.
    pub additional_safety_intervals: u64,
    /// The number of expected intervals per session.
    pub expected_intervals_per_session: NonZeroU64,
    /// The number of rounds per interval.
    pub rounds_per_interval: NonZeroU64,
    /// The maximum number of messages to generate in this session, before
    /// accounting for any generated data messages.
    pub message_count: u64,
}

#[cfg(test)]
mod tests {
    use core::task::{Context, Poll};

    use futures::{StreamExt as _, io::empty, task::noop_waker_ref};
    use rand::rngs::OsRng;
    use tokio_stream::iter;

    use crate::cover_traffic::SessionCoverTraffic;

    #[tokio::test]
    async fn no_emission_on_empty_schedule() {
        let mut scheduler = SessionCoverTraffic {
            round_clock: iter([0u128]).map(Into::into),
            remaining_messages: 0,
            remaining_rounds: 1.into(),
            unprocessed_data_messages: 0,
            rng: OsRng,
        };
        let mut cx = Context::from_waker(noop_waker_ref());

        assert_eq!(scheduler.poll_next_unpin(&mut cx), Poll::Pending);
    }

    #[tokio::test]
    async fn no_emission_on_unscheduled_round() {
        let mut scheduler = SessionCoverTraffic {
            round_clock: iter([0u128]).map(Into::into),
            remaining_messages: 0,
            remaining_rounds: 0.into(),
            unprocessed_data_messages: 0,
            rng: OsRng,
        };
        let mut cx = Context::from_waker(noop_waker_ref());

        assert_eq!(scheduler.poll_next_unpin(&mut cx), Poll::Pending);
    }

    #[tokio::test]
    async fn emission_on_scheduled_round_without_processed_messages() {
        // With remaining_messages == remaining_rounds, probability is 1.0,
        // so this round is guaranteed to be a release round.
        let mut scheduler = SessionCoverTraffic {
            round_clock: iter([0u128]).map(Into::into),
            remaining_messages: 1,
            remaining_rounds: 1.into(),
            unprocessed_data_messages: 0,
            rng: OsRng,
        };
        let mut cx = Context::from_waker(noop_waker_ref());

        assert_eq!(scheduler.poll_next_unpin(&mut cx), Poll::Ready(Some(())));
        // Check that there is no scheduled round remaining.
        assert_eq!(scheduler.remaining_messages, 0);
    }

    #[tokio::test]
    async fn no_emission_on_scheduled_round_with_single_unprocessed_message() {
        // remaining_messages == remaining_rounds == 1, so the round is
        // guaranteed to be a release round. With 1 unprocessed data message
        // and 1 pending cover message, the skip threshold is 1/1 = 1.0, so
        // the cover message is always skipped.
        let mut scheduler = SessionCoverTraffic {
            round_clock: iter([0u128]).map(Into::into),
            remaining_messages: 1,
            remaining_rounds: 1.into(),
            unprocessed_data_messages: 1,
            rng: OsRng,
        };
        let mut cx = Context::from_waker(noop_waker_ref());

        assert_eq!(scheduler.poll_next_unpin(&mut cx), Poll::Pending);
        // Check that there is no scheduled round remaining.
        assert_eq!(scheduler.remaining_messages, 0);
        // Check that the number of processed messages has been decremented.
        assert_eq!(scheduler.unprocessed_data_messages, 0);
    }

    #[tokio::test]
    async fn no_emission_on_scheduled_round_with_multiple_unprocessed_messages() {
        // remaining_messages == remaining_rounds == 3 guarantees every round
        // is a release round. With 2 unprocessed data messages, exactly 2
        // release rounds will be skipped and 1 cover message will be emitted.
        let mut scheduler = SessionCoverTraffic {
            round_clock: iter([0u128, 1u128, 2u128]).map(Into::into),
            remaining_messages: 3,
            remaining_rounds: 3.into(),
            unprocessed_data_messages: 2,
            rng: OsRng,
        };
        let mut cx = Context::from_waker(noop_waker_ref());

        let cover_message_count = (0u8..=2).fold(0u8, |count, _| {
            if scheduler.poll_next_unpin(&mut cx) == Poll::Ready(Some(())) {
                count + 1
            } else {
                count
            }
        });

        // Out of `3` scheduled release rounds, only one will yield a cover message,
        // since there's `2` unprocessed data messages.
        assert_eq!(cover_message_count, 1);
        // Check that the number of processed messages has been consumed.
        assert_eq!(scheduler.unprocessed_data_messages, 0);
    }

    #[test]
    fn notify_new_data_message_without_scheduled_rounds() {
        let mut scheduler = SessionCoverTraffic {
            round_clock: empty(),
            remaining_messages: 0,
            remaining_rounds: 0.into(),
            unprocessed_data_messages: 0,
            rng: OsRng,
        };
        scheduler.notify_new_data_message();
        assert_eq!(scheduler.unprocessed_data_messages, 1);
    }

    #[test]
    fn notify_new_data_message_with_scheduled_rounds() {
        let mut scheduler = SessionCoverTraffic {
            round_clock: empty(),
            remaining_messages: 1,
            remaining_rounds: 1.into(),
            unprocessed_data_messages: 0,
            rng: OsRng,
        };
        scheduler.notify_new_data_message();
        assert_eq!(scheduler.unprocessed_data_messages, 1);
    }
}
